name: Push Branch
on:
  workflow_call:
jobs:
  push-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          ref: 'main'
          sparse-checkout: .github/scripts
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npx bun .github/scripts/push-branch.ts
